language: node_js
node_js:
- '6'
before_install:
  # we want npm 4 for the prepublishOnly behavior
  - "npm install -g npm@^4"
cache: yarn
before_deploy:
  - "yarn manualPrepublish"
deploy:
  provider: npm
  email: kegan+isogon@keganmyers.com
  skip_cleanup: true
  on:
    tags: true
    repo: isogon/deploy-package-helper
